// svelte/src/Views/BasicDetails/BasicDetails.svelte
<script>
    import { Row, Col } from "sveltestrap";
    import Card from "../../components/Card/Card.svelte";

    export let username;
    export let url = "https://api.github.com/users/";
    
    const fetchDetails = (async () => {
        const response = await fetch(url+username);
        return await response.json();
    })();
</script>

{#await fetchDetails}
    <Row>
        <Col>
            <h3>Waiting....</h3>
        </Col>
    </Row>
{:then data}
    <Row>
        <Col>
            <Card
                color="cherry"
                title="Repos"
                text={data.public_repos}
                icon="layers"
            />
        </Col>
        <Col>
            <Card
                color="blue-dark"
                title="Gists"
                text={data.public_gists}
                icon="journals"
            />
        </Col>
        <Col>
            <Card
                color="green-dark"
                title="Followers"
                text={data.followers}
                icon="person-plus"
            />
        </Col>
        <Col>
            <Card
                color="orange-dark"
                title="Stars"
                text={data.following}
                icon="star"
            />
        </Col>
    </Row>
{:catch error}
    <Row>
        <Col>
            <h3>Oops! An error occured</h3>
        </Col>
    </Row>
{/await}

// reactjs/src/views/BasicDetails/BasicDetails.js
import React, { useEffect, useState } from "react"
import { Row, Col } from 'react-bootstrap';
import Datacard from "../../components/Datacard";

function BasicDetails(props) {
    const [repos, setRepos] = useState("");
    const [gists, setGists] = useState("");
    const [followers, setFollowers] = useState("");
    const [following, setFollowing] = useState("");
    const [error, setError] = useState("");

    useEffect(() => {
        const url = "https://api.github.com/users/saisyam";

        const fetchData = async () => {
            try {
                const response = await fetch(url);
                const data = await response.json();
                setRepos(data.public_repos);
                setGists(data.public_gists);
                setFollowers(data.followers);
                setFollowing(data.following);
            } catch (error) {
                setError(error);
            }
        };

        fetchData();
    }, []);

    return (
        <Row>
            <Col>
                <Datacard
                    color="cherry"
                    title="Repos"
                    text={repos}
                    icon="layers"
                />
            </Col>
            <Col>
                <Datacard
                    color="blue-dark"
                    title="Gists"
                    text={gists}
                    icon="journals"
                />
            </Col>
            <Col>   
                <Datacard
                    color="green-dark"
                    title="Followers"
                    text={followers}
                    icon="person-plus"
                />
            </Col>
            <Col>
                <Datacard
                    color="orange-dark"
                    title="Stars"
                    text={following}
                    icon="star"
                />
            </Col>
        </Row>
    );
};

export default BasicDetails;
