// src/components/Navbar/Navbar.svelte
<script>
    import {
      Collapse,
      Navbar,
      NavbarToggler,
      NavbarBrand,
      Nav,
      NavItem,
      NavLink,
      Dropdown,
      DropdownToggle,
      DropdownMenu,
      DropdownItem,
    } from 'sveltestrap';
  
    let isOpen = false;
  
    function handleUpdate(event) {
      isOpen = event.detail.isOpen;
    }
  </script>

  <Navbar color="primary" light expand="md" fixed="top">
    <NavbarBrand href="/">Github Analytics</NavbarBrand>
    <NavbarToggler on:click={() => (isOpen = !isOpen)} />
    <Collapse {isOpen} navbar expand="md" on:update={handleUpdate}>
      <Nav class="ms-auto" navbar>
        <NavItem>
          <NavLink href="/">Dashboard</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="/#repositories">Repos</NavLink>
        </NavItem>
      </Nav>
    </Collapse>
  </Navbar>

// reactjs/src/components/NavBar/NavBar.js
import {
    Navbar,
    Container,
    Nav
  } from 'react-bootstrap'
  
  function NavBar() {
    return (
      <Navbar bg="primary" expand="lg">
        <Container>
          <Navbar.Brand href="#home">Github Analytics</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav" className="justify-end">
            <Nav className="ms-auto">
              <Nav.Link href="#home">Dashboard</Nav.Link>
              <Nav.Link href="#link">Repos</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    );
  }
  
  export default NavBar;
